require_relative '../../../../node_modules/.bun/@capacitor+ios@7.6.8+9556538e6e670b78/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.bun/@capacitor+ios@7.6.8+9556538e6e670b78/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.bun/@capacitor+ios@7.6.8+9556538e6e670b78/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../../node_modules/.bun/@capacitor+app@7.1.2+9556538e6e670b78/node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../../../node_modules/.bun/@capacitor+browser@7.0.5+9556538e6e670b78/node_modules/@capacitor/browser'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/.bun/@capacitor+preferences@7.0.4+9556538e6e670b78/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../../../node_modules/.bun/@capacitor+push-notifications@7.0.7+9556538e6e670b78/node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../../../node_modules/.bun/@capacitor+share@7.0.4+9556538e6e670b78/node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../../../node_modules/.bun/@capacitor+splash-screen@7.0.5+9556538e6e670b78/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../../../node_modules/.bun/@capacitor+status-bar@7.0.6+9556538e6e670b78/node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
